export const PropKeys = {
  COLOR: 'color',
  TAG: 'tag',
  SIZE: 'size',
  FONT: 'font',
  TRANSFORM: 'transform',
  LETTER_SPACING: 'letterSpacing',
  LINE_HEIGHT: 'lineHeight',
  ALIGN: 'align',
};

export const PropValues = {
  [PropKeys.COLOR]: ['inherit'],
  [PropKeys.TAG]: [
    'a',
    'nuxt-link',
    'router-link',
    'address',
    'time',
    'span',
    'strong',
    'div',
    'p',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'address',
    'li',
    'blockquote',
    'dt',
    'dd',
    'figcaption',
  ],
  [PropKeys.SIZE]: ['3xs', '2xs', 'xs', 'sm', 'base', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'],
  [PropKeys.FONT]: ['default', 'bold', 'mono'],
  [PropKeys.TRANSFORM]: ['default', 'uppercase'],
  [PropKeys.LETTER_SPACING]: ['default', 'md', 'lg', 'xl'],
  [PropKeys.LINE_HEIGHT]: ['3xs', '2xs', 'xs', 'sm', 'base', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'],
  [PropKeys.ALIGN]: ['default', 'center', 'right'],
};
